### ISSUE TITLE
Can you give some more information?

### ISSUE THREAD

**Issue by alonhar** [jbedo/boogiesync-tablet#1]
I am using boogieboard sync on linux arch.
I connected to the device and now what?? their is a program that use this option?
cause the mouse does not move..

I think that the blue.py cant go over line data = sock.recv(1024) .
thanks,

**Comment by jbedo** [comment]
Hi!

Thanks for trying out the program.  Sounds like the payload to knock the device into tablet mode isn't working for you if it gets stuck on that line.  Are you running the latest firmware?  I only have one boogie board so I'm unable to test this very well.  It's also possible the payload needs to be device specific, which will be a bit difficult to reverse engineer.

The way I worked out the payload was by sniffing bluetooth traffic on my android phone while activating the tablet drawing mode with the boogieboard app.  If you are able to do this then we may be able to work out the correct payload for your device the same way.

**Comment by alonhar** [comment]
I have sniff file of the bluetooth.
this is the file https://www.dropbox.com/s/hir2f212mflskcr/btsnoop_hci%20%281%29.log?dl=0
I can open it with wireshark
which parameters I need to change?

**Comment by jbedo** [comment]
Sorry for the delay.  I've dug through your log a bit and found it's sending the same payload and receiving the same response as my boogie board (packet 210 is the payload, packet 213 the response), so I don't think that's the problem.  Just to verify, when you run blue.py does it output "connected" and then hang?

**Comment by alonhar** [comment]
it's wait for something in this line  data = sock.recv(1024)
it's not crash of exit the app.
