### ISSUE TITLE
Issue both with bluetooth and usb...

### ISSUE THREAD

**Issue by qazerd** [jbedo/boogiesync-tablet#11]
---with usb
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
...
payload transfer failed, retrying

 File "usb-driver.py", line 57, in <module>
    ui = UInput(cap, name='boogie-board-sync-pen')
  File "/usr/local/lib/python2.7/dist-packages/evdev/uinput.py", line 136, in __init__
    _uinput.create(self.fd, name, vendor, product, version, bustype, absinfo)
IOError: [Errno 22] Invalid argument

--- with bluetooth
Searching for boogie board sync on A0:E6:F8:A0:9B:CA
connecting to "HID over SPP" on A0:E6:F8:A0:9B:CA
connected
good response
Traceback (most recent call last):
  File "blue.py", line 69, in <module>
    ui = UInput(cap, name='boogie-board-sync')
  File "/usr/local/lib/python2.7/dist-packages/evdev/uinput.py", line 136, in __init__
    _uinput.create(self.fd, name, vendor, product, version, bustype, absinfo)
IOError: [Errno 22] Invalid argument

hope it will help

**Comment by jbedo** [comment]
I've seen this before, the problem is with your evdev installation. Try reinstalling evdev.

**Comment by Zajozor** [comment]
Hi, here on Archlinux 4.11-rt, Alienware 15R2,  having the same error as described above

using with python 3
reinstalled packages: libevdev python-evdev xf86-input-evdev

still no change, could you give us some other clues to follow on getting BBS to work ?

thanks :)

**Comment by jbedo** [comment]
What version evdev and kernel?

**Comment by Zajozor** [comment]
```
libevdev 1.5.7-1
python-evdev 0.7.0-1
xf86-input-evdev 2.10.5-1
```

Are there recommended versions ?

```
$ uname -a
Linux zor-resurrected 4.11.12-1-rt16-MANJARO #1 SMP PREEMPT RT Tue Oct 17 18:15:30 UTC 2017 x86_64 GNU/Linux
```

**Comment by jbedo** [comment]
I think it was my old bug workaround, can you try the evdev branch?

https://github.com/jbedo/boogiesync-tablet/tree/evdev

**Comment by Zajozor** [comment]
got USB working. Rocking and functional for now, thanks :)

**Comment by jbedo** [comment]
Great, enjoy!
