### ISSUE TITLE
IOError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by Shagu17** [jbedo/boogiesync-tablet#13]
Dear Jbedo,
thanks a lot for your work. I am not the Python crack so maybe I am doing something wrong, but I get the message:

**connected
good response
Traceback (most recent call last):
  File "blue.py", line 68, in <module>
    ui = UInput(cap, name='boogie-board-sync')
  File "/usr/lib/python2.7/dist-packages/evdev/uinput.py", line 83, in __init__
    _uinput.create(self.fd, name, vendor, product, version, bustype, absinfo)
IOError: [Errno 22] Invalid argument**

When I look at the script it only has { UInput(cap, name='boogie-board-sync') } two parameters and not seven as it mentions. So I guess it is something with that? I am running it with Python2, because my pybluez only works with that version and I cannot get one for Python3 running. 

Cheers
Shagu

**Comment by jbedo** [comment]
What version of evdev are you running? The problem isn't the number of parameters, you need to look higher in the stack (says problem is on line 68 of blue.py higher up). I've pushed a small change that renames the input to have the -pen suffix, like the USB version. Can you try this?

Otherwise, does the USB version work for you?

**Comment by Shagu17** [comment]
Wow, thank you for the quick response.

On Linux Mint 18.3

libevdev2: 1.4.6+dfsg-1
python-evdev and python3-evdev: 0.4.7-0ubuntu4

python: 2.7.12
python3: 3.5.2

python-bluez: 0.22-1

python-usb and python3-usb: 1.0.0~b2-2


### USB Version ###

**The USB version doesn't do anything for me. For python 2.7.12:
payload transfer failed, retrying      # ( Multiple Times )
Payload sent
Traceback (most recent call last):
  File "usb-driver.py", line 63, in <module>
    raise err
usb.core.USBError: [Errno 5] Input/Output Error**

And Python 3.5.2 does not bring an error, but it shows much more payload transfer failed until it sends its Payload sent. After it reaches Payload sent it keeps the program running, but writing on the tablet does not change anything with the mouse cursor. Do I have to use a program to see any changes / use it to draw?


### Blue Version ###

There is an indent error on line 78, but after that it brings the same message.

**connected
good response
Traceback (most recent call last):
  File "blue.py", line 67, in <module>
    ui = UInput(cap, name='boogie-board-sync-pen')
  File "/usr/lib/python2.7/dist-packages/evdev/uinput.py", line 83, in __init__
    _uinput.create(self.fd, name, vendor, product, version, bustype, absinfo)
IOError: [Errno 22] Invalid argument**

if I take out the line ui = UInput(cap, name='boogie-board-sync-pen') as long as I do not touch the tablet. If I do it cannot find ui ;-)

**Comment by jbedo** [comment]
Yeah the payload resending thing for the usb version is annoying, but I never did find a way to get it to work more reliably. In any case, if it finally sends the payload then goes quiet it should be working, and you don't need to do anything except use your pen and the mouse cursor should move.

I suggest adding some debugging output on line 68 of the usb version like "print xpos, ypos". If you see a bunch of coordinates being dumped to stdout, then the tablets working find and its definitely evdev that's broken.

Your libevdev and python evdev are quite old,  so this probably is causing issues. For reference, I'm running python evdev 0.7.0 with libevdev 1.5.7. Maybe try updated your python evdev to 0.7.0?

**Comment by Shagu17** [comment]
I changed from Linux Mint 18.3 to Ubuntu 18.04 daily because Mint started to have too many freezes. Now my evdev is at 0.7.0 and the usb one is working like a charm ;-) Thanks a lot
