### ISSUE TITLE
ImportError: No module named evdev

### ISSUE THREAD

**Issue by 243750496** [jbedo/boogiesync-tablet#6]
cc@CC:~/boogiesync-tablet-master$ ./blue.py 00:17:E9:88:AA:D2
Traceback (most recent call last):
  File "./blue.py", line 3, in <module>
    from evdev import UInput, AbsInfo, ecodes as e
ImportError: No module named evdev

**Comment by 243750496** [comment]
cc@CC:~/boogiesync-tablet-master$ ./usb-driver.py
Traceback (most recent call last):
  File "./usb-driver.py", line 3, in <module>
    import usb.core
ImportError: No module named usb.core

**Comment by jbedo** [comment]
Have you got pyusb and evdev installed?

**Comment by 243750496** [comment]
> cc@CC:~$ pip install --pre pyusb
> Collecting pyusb
>   Downloading PyUSB-1.0.0.tar.gz (52kB)
>     100% |████████████████████████████████| 61kB 228kB/s 
> Building wheels for collected packages: pyusb
>   Running setup.py bdist_wheel for pyusb ... done
>   Stored in directory: /home/cc/.cache/pip/wheels/18/b0/b8/83d67cc7a3b50866f908ca1104b553f7807e1e767ddf373427
> Successfully built pyusb
> Installing collected packages: pyusb
> Successfully installed pyusb
> You are using pip version 8.1.1, however version 9.0.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> cc@CC:~$ pip install --upgrade pip
> Collecting pip
>   Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
>     100% |████████████████████████████████| 1.3MB 684kB/s 
> Installing collected packages: pip
> Successfully installed pip-9.0.1
> cc@CC:~$ pip install --pre pyusb
> Requirement already satisfied: pyusb in ./.local/lib/python2.7/site-packages
> cc@CC:~$ pip install --pre evdev
> Collecting evdev
>   Downloading evdev-0.6.4.tar.gz
> Building wheels for collected packages: evdev
>   Running setup.py bdist_wheel for evdev ... done
>   Stored in directory: /home/cc/.cache/pip/wheels/64/4e/61/20afc41b2f932f4e520fff9f8d70c063eab38c21dc0e5d9d62
> Successfully built evdev
> Installing collected packages: evdev
> Exception:
> Traceback (most recent call last):
>   File "/home/cc/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
>     status = self.run(options, args)
>   File "/home/cc/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
>     prefix=options.prefix_path,
>   File "/home/cc/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
>     **kwargs
>   File "/home/cc/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
>     self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
>   File "/home/cc/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
>     isolated=self.isolated,
>   File "/home/cc/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
>     clobber(source, lib_dir, True)
>   File "/home/cc/.local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
>     ensure_dir(destdir)
>   File "/home/cc/.local/lib/python2.7/site-packages/pip/utils/**init**.py", line 83, in ensure_dir
>     os.makedirs(path)
>   File "/usr/lib/python2.7/os.py", line 157, in makedirs
>     mkdir(name, mode)
> OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/evdev-0.6.4.dist-info'
> cc@CC:~$ sudo pip install --pre evdev
> The directory '/home/cc/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> The directory '/home/cc/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> Collecting evdev
> Installing collected packages: evdev
> Successfully installed evdev-0.6.4
> cc@CC:~$ sudo pip install --pre evdev
> The directory '/home/cc/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> The directory '/home/cc/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> Requirement already satisfied: evdev in /usr/local/lib/python2.7/dist-packages

cc@CC:~$ cd '/home/cc/boogiesync-tablet-master' 
**cc@CC:~/boogiesync-tablet-master$ ./blue.py 00:17:E9:88:AA:D2
Traceback (most recent call last):
  File "./blue.py", line 4, in <module>
    from bluetooth import *
ImportError: No module named bluetooth**

**Comment by 243750496** [comment]
cc@CC:~/boogiesync-tablet-master$ sudo ./usb-driver.py
\Payload sent
Traceback (most recent call last):
  File "./usb-driver.py", line 57, in <module>
    ui = UInput(cap, name='boogie-board-sync-pen')
  File "/usr/local/lib/python2.7/dist-packages/evdev/uinput.py", line 136, in **init**
    _uinput.create(self.fd, name, vendor, product, version, bustype, absinfo)
IOError: [Errno 22] Invalid argument
cc@CC:~/boogiesync-tablet-master$ \
